# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

predict_gpd_params_cpp <- function(init_pars, data, weights_mat, lambda, xi_prior, intermediate_quantile) {
    .Call(`_erf_predict_gpd_params_cpp`, init_pars, data, weights_mat, lambda, xi_prior, intermediate_quantile)
}

weighted_llh <- function(par, data, weights, lambda, xi_prior, intermediate_quantile) {
    .Call(`_erf_weighted_llh`, par, data, weights, lambda, xi_prior, intermediate_quantile)
}

