# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

weighted_llh <- function(par, data, weights, lambda, xi_prior) {
    .Call(`_erf_weighted_llh`, par, data, weights, lambda, xi_prior)
}

